PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ano ?nivel
  (COUNT(DISTINCT ?autor) AS ?totalAutores)
  (AVG(xsd:integer(?nrCitacoes)) AS ?mediaCitacoes)
  (AVG(xsd:integer(?indiceH)) AS ?mediaIndiceH)
WHERE {
  ?discente a cti:Discente ;
            cti:id_pessoa ?idPessoa ;
            cti:ds_grau_academico_discente ?nivel ;
            cti:vinculado ?ppg .

  ?ppg cti:sediado ?ict .
  ?ict cti:sg_entidade_ensino "UFRPE" .

  ?discente cti:an_titulacao ?ano .
  FILTER(xsd:integer(?ano) >= {ano_inicio} && xsd:integer(?ano) <= {ano_fim})

  ?autor a cti:Autor ;
         cti:id_pessoa ?idPessoa ;
         cti:mensurado ?citacao .

  ?citacao cti:nr_citacoes_autor ?nrCitacoes ;
           cti:nr_indice_h ?indiceH .
}
GROUP BY ?ano ?nivel
ORDER BY ?ano ?nivel
