PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?nomeAutor ?indiceH ?nrCitacoesAutor (COUNT(DISTINCT ?prod) AS ?totalPublicacoes)
WHERE {
  ?autor a cti:Autor ;
         cti:nm_pessoa ?nomeAutor ;
         cti:autoria ?prod ;
         cti:mensurado ?citacao .
  ?citacao cti:nr_indice_h ?indiceH ;
           cti:nr_citacoes_autor ?nrCitacoesAutor .
}
GROUP BY ?nomeAutor ?indiceH ?nrCitacoesAutor
ORDER BY DESC(xsd:integer(?indiceH)) DESC(xsd:integer(?nrCitacoesAutor))
