PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?conceito ?nivel
  (COUNT(DISTINCT ?autor)        AS ?totalAutores)
  (AVG(?nrCitacoes)              AS ?mediaCitacoes)
  (AVG(xsd:integer(?indiceH))    AS ?mediaIndiceH)
WHERE {
  {
    ?discente a cti:Discente ;
              cti:id_pessoa ?idPessoa ;
              cti:ds_grau_academico_discente ?nivel ;
              cti:an_titulacao ?ano ;
              cti:vinculado ?ppg .
    
    ?ppg cti:sediado ?ict ;
         cti:avaliado ?c_obj .
    ?ict cti:sg_entidade_ensino "UFRPE" .
    
    ?c_obj cti:cd_conceito_programa ?conceito ;
           cti:an_base_conceito ?anoConceito .
    
    FILTER(xsd:integer(?anoConceito) = xsd:integer(?ano))
    FILTER(xsd:integer(?ano) >= {ano_inicio} && xsd:integer(?ano) <= {ano_fim})
    
    ?autor a cti:Autor ;
           cti:id_pessoa ?idPessoa ;
           cti:mensurado ?citacao .
    
    ?citacao cti:nr_citacoes_autor ?nrCitacoes ;
             cti:nr_indice_h ?indiceH .
  }
  UNION
  {
    ?discente a cti:Discente ;
              cti:id_pessoa ?idPessoa ;
              cti:ds_grau_academico_discente ?nivel ;
              cti:an_titulacao ?ano ;
              cti:vinculado ?ppg .
    
    ?ppg cti:sediado ?ict ;
         cti:avaliado ?c_obj .
    ?ict cti:sg_entidade_ensino "UFRPE" .
    
    ?c_obj cti:cd_conceito_programa ?conceito ;
           cti:an_base_conceito ?anoConceito .
    
    FILTER(xsd:integer(?anoConceito) = xsd:integer(?ano) - 1)
    FILTER(xsd:integer(?ano) >= {ano_inicio} && xsd:integer(?ano) <= {ano_fim})
    
    ?autor a cti:Autor ;
           cti:id_pessoa ?idPessoa ;
           cti:mensurado ?citacao .
    
    ?citacao cti:nr_citacoes_autor ?nrCitacoes ;
             cti:nr_indice_h ?indiceH .
  }
}
GROUP BY ?conceito ?nivel
ORDER BY ?conceito ?nivel