PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?conceito (AVG(xsd:integer(?nrCitacoesAutor)) AS ?mediaCitacoes)
WHERE {
  {
    SELECT DISTINCT ?conceito ?autor ?nrCitacoesAutor
    WHERE {
      ?ppg a cti:PPG ;
           cti:avaliado ?c_obj .
      ?c_obj cti:cd_conceito_programa ?conceito .

      ?discente a cti:Discente ;
                cti:vinculado ?ppg ;
                cti:id_pessoa ?id_comum .

      ?autor a cti:Autor ;
             cti:id_pessoa ?id_comum ;
             cti:mensurado ?citacao .

      ?citacao cti:nr_citacoes_autor ?nrCitacoesAutor .
    }
  }
}
GROUP BY ?conceito
ORDER BY DESC(?conceito)