PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?nivel
  (COUNT(DISTINCT ?autor) AS ?totalAutores)
  (COUNT(DISTINCT ?prod) AS ?totalProducoes)
  (xsd:decimal(COUNT(DISTINCT ?prod)) / xsd:decimal(COUNT(DISTINCT ?autor)) AS ?mediaProducoesPorAutor)
WHERE {
  ?discente a cti:Discente ;
            cti:id_pessoa ?idPessoa ;
            cti:ds_grau_academico_discente ?nivel ;
            cti:vinculado ?ppg .
  ?ppg cti:sediado ?ict .
  ?ict cti:sg_entidade_ensino "UFRPE" .

  ?autor a cti:Autor ;
         cti:id_pessoa ?idPessoa ;
         cti:autoria ?prod .
}
GROUP BY ?nivel
ORDER BY ?nivel
