PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ano ?nivel
  (COUNT(DISTINCT ?discente) AS ?totalDiscentes)
  (COUNT(DISTINCT ?prod) AS ?totalProducoes)
WHERE {
  ?discente a cti:Discente ;
            cti:id_pessoa ?idPessoa ;
            cti:ds_grau_academico_discente ?nivel ;
            cti:vinculado ?ppg .
  ?ppg cti:sediado ?ict ;
       cti:avaliado ?c_obj .
  ?ict cti:sg_entidade_ensino "UFRPE" .
  ?c_obj cti:an_base_conceito ?ano .
  FILTER(xsd:integer(?ano) >= {ano_inicio} && xsd:integer(?ano) <= {ano_fim})

  OPTIONAL {
    ?autor a cti:Autor ;
           cti:id_pessoa ?idPessoa ;
           cti:autoria ?prod .
  }
}
GROUP BY ?ano ?nivel
ORDER BY ?ano ?nivel