PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT ?nomePPG ?conceito ?mediaCiteScore
WHERE {
  ?ppg a cti:PPG ;
       cti:nm_programa_ies ?nomePPG ;
       cti:avaliado ?conceitoInd .
  
  ?conceitoInd cti:cd_conceito_programa ?conceito ;
               cti:an_base_conceito 2024 .
               
  ?discente cti:vinculado ?ppg .
  ?autor a cti:Autor ;
         cti:id_pessoa ?id ;
         cti:autoria ?artigo .
  
  # Vinculando Autor ao Discente pelo ID (assumindo que são a mesma pessoa)
  ?discente cti:id_pessoa ?id .
  
  ?artigo cti:publicada ?veiculo .
  ?veiculo cti:nr_citescore_scopus ?score .
}
GROUP BY ?nomePPG ?conceito
ORDER BY DESC(?conceito)