# Configuração do Jekyll para GitHub Pages
title: "🔬 CT&I-PE"
description: "Portal de Gestão do Conhecimento - Ciência, Tecnologia e Inovação de Pernambuco"
author: "Lucas Xavier, Caio Nogueira, Vinícius Souza"
url: "https://github.com/Lucas-X-A/Projeto_Gestao_da_Informacao"
baseurl: "/Projeto_Gestao_da_Informacao"

# Tema
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Configurações de build
markdown: kramdown
highlighter: rouge
